name: Build

on:
  workflow_call:
    inputs:
      push_image:
        description: 'Om bygget image skal pushes eller ikke'
        type: boolean
        default: true
        required: false
      gradle_project:
        description: 'Gradle-prosjektet som skal bygges'
        type: string
        default: ':sp-forsikring'
        required: false
      docker_target:
        description: 'Target stage i Dockerfile'
        type: string
        default: 'sp-forsikring'
        required: false
      image_suffix:
        description: 'Suffix for Docker-image'
        type: string
        default: ''
        required: false
    outputs:
      image:
        description: "Navn på imaget som ble bygget"
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: read
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Fetch all history for what-changed action

      - name: Determine what to do
        id: changed-files
        uses: "nais/what-changed@main"
        with:
          files: '.nais/*'

      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: temurin
          java-version: 25

      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          languages: java-kotlin
          build-mode: manual
          queries: security-extended,security-and-quality
          config: |
            threat-models: local

      - name: gradle build installDist
        run: ./gradlew ${{ inputs.gradle_project }}:build ${{ inputs.gradle_project }}:installDist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0

      - name: Build and push image and SBOM to OCI registry
        if: steps.changed-files.outputs.changed != 'only-inputs'
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-build-push
        with:
          team: tbd
          push_image: ${{ inputs.push_image }}
          dockerfile: Dockerfile
          docker_context: .
          image_suffix: ${{ inputs.image_suffix }}
          target: ${{ inputs.docker_target }}
