name: Bygg og deploy main

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 3'
      timezone: 'Europe/Oslo'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  bygg-og-test:
    uses: ./.github/workflows/bygg-og-test.yml
    secrets: inherit
    with:
      push_image: true

  deploy:
    name: Deploy (${{ matrix.module }})
    needs: bygg-og-test
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: sp-forsikring
            resource: .nais/sp-forsikring.yaml
            dev_vars: .nais/sp-forsikring-vars-dev.yaml
            prod_vars: .nais/sp-forsikring-vars-prod.yaml
          - module: opprydding-dev
            resource: '.nais/opprydding-dev.yaml, .nais/dev-db-policy.yaml'
            dev_vars: /dev/null
            prod_vars: ''
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ matrix.resource }}
          VARS: ${{ matrix.dev_vars }}
          WORKLOAD_IMAGE: ${{ fromJson(needs.bygg-og-test.outputs.images)[matrix.module] }}

      - name: Deploy til prod
        if: matrix.prod_vars != ''
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ${{ matrix.resource }}
          VARS: ${{ matrix.prod_vars }}
          WORKLOAD_IMAGE: ${{ fromJson(needs.bygg-og-test.outputs.images)[matrix.module] }}
