name: main - sp-forsikring - Bygg, test og deploy

on:
  push:
    branches:
      - main
    paths:
      # Generelt oppsett - alt unntatt dokumentasjon / urelatert oppsett
      - '**'
      - '!**.md'
      - '!CODEOWNERS'
      - '!LICENSE'
      - '!docs/**'
      - '!.nais/**'
      - '!.github/workflows/standard-dependabot-auto-merge.yml'
      - '!.github/workflows/standard-dependency-submission.yml'
      # Ressursene som deployes av denne workflowen
      - '.nais/sp-forsikring.yaml'
      - '.nais/sp-forsikring.*.yaml'
      - '.nais/dev-spleis-testdata-replikabase-policy.yaml'
      # Spesielt for denne tjenesten ellers
      - '!.github/workflows/standard-pr.yml'
      - '!.github/workflows/main-opprydding-dev.yml'
      - '!opprydding-dev/**'
  schedule:
    - cron: '0 4 * * 3'
      timezone: 'Europe/Oslo'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read # for sarif
  contents: read
  security-events: write # push sarif to github security
  id-token: write # for nais login

jobs:
  bygg-og-test:
    name: Bygg og test
    uses: navikt/sykepenger-github-workflows/.github/workflows/bygg-og-test-med-gradle.yml@a3796daf68dadd20000651bc347190c71acda4ba # v1.0.7
    permissions:
      contents: read

  bygg-image:
    name: Bygg image
    needs: bygg-og-test
    uses: navikt/sykepenger-github-workflows/.github/workflows/bygg-modul-image-med-jib.yml@a3796daf68dadd20000651bc347190c71acda4ba # v1.0.7
    with:
      modul: sp-forsikring
    permissions:
      actions: read # for sarif upload on private repos
      contents: read
      id-token: write # for nais login
      security-events: write # push sarif to github security

  deploy-dev:
    name: Deploy til dev
    needs: bygg-image
    uses: navikt/sykepenger-github-workflows/.github/workflows/deploy-v2.yml@a3796daf68dadd20000651bc347190c71acda4ba # v1.0.7
    with:
      manifest: .nais/sp-forsikring.yaml
      environment: dev-gcp
      image: ${{ needs.bygg-image.outputs.image_ref }}
      extra_manifests: .nais/dev-spleis-testdata-replikabase-policy.yaml
    permissions:
      contents: read
      id-token: write # for nais login

  deploy-prod:
    name: Deploy til prod
    needs: bygg-image
    uses: navikt/sykepenger-github-workflows/.github/workflows/deploy-v2.yml@a3796daf68dadd20000651bc347190c71acda4ba # v1.0.7
    with:
      manifest: .nais/sp-forsikring.yaml
      environment: prod-gcp
      image: ${{ needs.bygg-image.outputs.image_ref }}
    permissions:
      contents: read
      id-token: write # for nais login
