name: Bygg og deploy opprydding-dev

on:
  push:
    branches:
      - main
    paths:
      - 'opprydding-dev/**'
      - 'migreringer/**'
      - '.github/workflows/opprydding-dev.yml'
      - '.github/workflows/build.yml'
      - '.nais/opprydding-dev.yaml'
      - '.nais/dev-db-policy.yaml'
      - 'Dockerfile'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - 'gradle/**'
  schedule:
    - cron: '0 4 * * 3'
      timezone: 'Europe/Oslo'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      gradle_project: ':opprydding-dev'
      docker_target: 'opprydding-dev'
      image_suffix: 'opprydding-dev'

  deployDev:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/opprydding-dev.yaml, .nais/dev-db-policy.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
