name: Bygg PR

on: [ pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  build-sp-forsikring:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      push_image: false
  build-opprydding-dev:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      push_image: false
      gradle_project: ':opprydding-dev'
      docker_context: 'opprydding-dev'
      image_suffix: 'opprydding-dev'
