name: Bygg PR

on: [ pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  bygg-og-test:
    uses: ./.github/workflows/bygg-og-test.yml
    secrets: inherit
    with:
      push_image: false
